<?php
/**
 * DocumentFormFields
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BoldSign\Model;

use \ArrayAccess;
use \BoldSign\ObjectSerializer;

/**
 * DocumentFormFields Class Doc Comment
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DocumentFormFields implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DocumentFormFields';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'form_field_id' => 'string',
        'type' => 'string',
        'value' => 'string',
        'font' => 'string',
        'is_required' => 'bool',
        'is_read_only' => 'bool',
        'line_height' => 'float',
        'font_size' => 'float',
        'font_color' => 'string',
        'is_underline' => 'bool',
        'is_italic' => 'bool',
        'is_bold' => 'bool',
        'group_name' => 'string',
        'label' => 'string',
        'placeholder' => 'string',
        'validationtype' => 'string',
        'validation_custom_regex' => 'string',
        'validation_custom_regex_message' => 'string',
        'date_format' => 'string',
        'time_format' => 'string',
        'image_info' => '\BoldSign\Model\ImageInfo',
        'attachment_info' => '\BoldSign\Model\AttachmentInfo',
        'file_info' => '\BoldSign\Model\FileInfo',
        'editable_date_field_settings' => '\BoldSign\Model\EditableDateFieldSettings',
        'hyperlink_text' => 'string',
        'conditional_rules' => '\BoldSign\Model\ConditionalRule[]',
        'bounds' => '\BoldSign\Model\Rectangle',
        'page_number' => 'int',
        'data_sync_tag' => 'string',
        'dropdown_options' => 'string[]',
        'text_align' => 'string',
        'text_direction' => 'string',
        'character_spacing' => 'float',
        'background_hex_color' => 'string',
        'tab_index' => 'int',
        'formula_field_settings' => '\BoldSign\Model\FormulaFieldSettings',
        'resize_option' => 'string',
        'allow_edit_form_field' => 'bool',
        'allow_delete_form_field' => 'bool',
        'collaboration_settings' => '\BoldSign\Model\CollaborationSettings',
        'hidden' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'form_field_id' => null,
        'type' => null,
        'value' => null,
        'font' => null,
        'is_required' => null,
        'is_read_only' => null,
        'line_height' => 'float',
        'font_size' => 'float',
        'font_color' => null,
        'is_underline' => null,
        'is_italic' => null,
        'is_bold' => null,
        'group_name' => null,
        'label' => null,
        'placeholder' => null,
        'validationtype' => null,
        'validation_custom_regex' => null,
        'validation_custom_regex_message' => null,
        'date_format' => null,
        'time_format' => null,
        'image_info' => null,
        'attachment_info' => null,
        'file_info' => null,
        'editable_date_field_settings' => null,
        'hyperlink_text' => null,
        'conditional_rules' => null,
        'bounds' => null,
        'page_number' => 'int32',
        'data_sync_tag' => null,
        'dropdown_options' => null,
        'text_align' => null,
        'text_direction' => null,
        'character_spacing' => 'float',
        'background_hex_color' => null,
        'tab_index' => 'int32',
        'formula_field_settings' => null,
        'resize_option' => null,
        'allow_edit_form_field' => null,
        'allow_delete_form_field' => null,
        'collaboration_settings' => null,
        'hidden' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => true,
        'form_field_id' => true,
        'type' => true,
        'value' => true,
        'font' => true,
        'is_required' => false,
        'is_read_only' => false,
        'line_height' => false,
        'font_size' => false,
        'font_color' => true,
        'is_underline' => false,
        'is_italic' => false,
        'is_bold' => false,
        'group_name' => true,
        'label' => true,
        'placeholder' => true,
        'validationtype' => false,
        'validation_custom_regex' => true,
        'validation_custom_regex_message' => true,
        'date_format' => true,
        'time_format' => true,
        'image_info' => false,
        'attachment_info' => false,
        'file_info' => false,
        'editable_date_field_settings' => false,
        'hyperlink_text' => true,
        'conditional_rules' => true,
        'bounds' => false,
        'page_number' => false,
        'data_sync_tag' => true,
        'dropdown_options' => true,
        'text_align' => false,
        'text_direction' => false,
        'character_spacing' => false,
        'background_hex_color' => true,
        'tab_index' => false,
        'formula_field_settings' => false,
        'resize_option' => true,
        'allow_edit_form_field' => false,
        'allow_delete_form_field' => false,
        'collaboration_settings' => false,
        'hidden' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'form_field_id' => 'formFieldId',
        'type' => 'type',
        'value' => 'value',
        'font' => 'font',
        'is_required' => 'isRequired',
        'is_read_only' => 'isReadOnly',
        'line_height' => 'lineHeight',
        'font_size' => 'fontSize',
        'font_color' => 'fontColor',
        'is_underline' => 'isUnderline',
        'is_italic' => 'isItalic',
        'is_bold' => 'isBold',
        'group_name' => 'groupName',
        'label' => 'label',
        'placeholder' => 'placeholder',
        'validationtype' => 'validationtype',
        'validation_custom_regex' => 'validationCustomRegex',
        'validation_custom_regex_message' => 'validationCustomRegexMessage',
        'date_format' => 'dateFormat',
        'time_format' => 'timeFormat',
        'image_info' => 'imageInfo',
        'attachment_info' => 'attachmentInfo',
        'file_info' => 'fileInfo',
        'editable_date_field_settings' => 'editableDateFieldSettings',
        'hyperlink_text' => 'hyperlinkText',
        'conditional_rules' => 'conditionalRules',
        'bounds' => 'bounds',
        'page_number' => 'pageNumber',
        'data_sync_tag' => 'dataSyncTag',
        'dropdown_options' => 'dropdownOptions',
        'text_align' => 'textAlign',
        'text_direction' => 'textDirection',
        'character_spacing' => 'characterSpacing',
        'background_hex_color' => 'backgroundHexColor',
        'tab_index' => 'tabIndex',
        'formula_field_settings' => 'formulaFieldSettings',
        'resize_option' => 'resizeOption',
        'allow_edit_form_field' => 'allowEditFormField',
        'allow_delete_form_field' => 'allowDeleteFormField',
        'collaboration_settings' => 'collaborationSettings',
        'hidden' => 'hidden'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'form_field_id' => 'setFormFieldId',
        'type' => 'setType',
        'value' => 'setValue',
        'font' => 'setFont',
        'is_required' => 'setIsRequired',
        'is_read_only' => 'setIsReadOnly',
        'line_height' => 'setLineHeight',
        'font_size' => 'setFontSize',
        'font_color' => 'setFontColor',
        'is_underline' => 'setIsUnderline',
        'is_italic' => 'setIsItalic',
        'is_bold' => 'setIsBold',
        'group_name' => 'setGroupName',
        'label' => 'setLabel',
        'placeholder' => 'setPlaceholder',
        'validationtype' => 'setValidationtype',
        'validation_custom_regex' => 'setValidationCustomRegex',
        'validation_custom_regex_message' => 'setValidationCustomRegexMessage',
        'date_format' => 'setDateFormat',
        'time_format' => 'setTimeFormat',
        'image_info' => 'setImageInfo',
        'attachment_info' => 'setAttachmentInfo',
        'file_info' => 'setFileInfo',
        'editable_date_field_settings' => 'setEditableDateFieldSettings',
        'hyperlink_text' => 'setHyperlinkText',
        'conditional_rules' => 'setConditionalRules',
        'bounds' => 'setBounds',
        'page_number' => 'setPageNumber',
        'data_sync_tag' => 'setDataSyncTag',
        'dropdown_options' => 'setDropdownOptions',
        'text_align' => 'setTextAlign',
        'text_direction' => 'setTextDirection',
        'character_spacing' => 'setCharacterSpacing',
        'background_hex_color' => 'setBackgroundHexColor',
        'tab_index' => 'setTabIndex',
        'formula_field_settings' => 'setFormulaFieldSettings',
        'resize_option' => 'setResizeOption',
        'allow_edit_form_field' => 'setAllowEditFormField',
        'allow_delete_form_field' => 'setAllowDeleteFormField',
        'collaboration_settings' => 'setCollaborationSettings',
        'hidden' => 'setHidden'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'form_field_id' => 'getFormFieldId',
        'type' => 'getType',
        'value' => 'getValue',
        'font' => 'getFont',
        'is_required' => 'getIsRequired',
        'is_read_only' => 'getIsReadOnly',
        'line_height' => 'getLineHeight',
        'font_size' => 'getFontSize',
        'font_color' => 'getFontColor',
        'is_underline' => 'getIsUnderline',
        'is_italic' => 'getIsItalic',
        'is_bold' => 'getIsBold',
        'group_name' => 'getGroupName',
        'label' => 'getLabel',
        'placeholder' => 'getPlaceholder',
        'validationtype' => 'getValidationtype',
        'validation_custom_regex' => 'getValidationCustomRegex',
        'validation_custom_regex_message' => 'getValidationCustomRegexMessage',
        'date_format' => 'getDateFormat',
        'time_format' => 'getTimeFormat',
        'image_info' => 'getImageInfo',
        'attachment_info' => 'getAttachmentInfo',
        'file_info' => 'getFileInfo',
        'editable_date_field_settings' => 'getEditableDateFieldSettings',
        'hyperlink_text' => 'getHyperlinkText',
        'conditional_rules' => 'getConditionalRules',
        'bounds' => 'getBounds',
        'page_number' => 'getPageNumber',
        'data_sync_tag' => 'getDataSyncTag',
        'dropdown_options' => 'getDropdownOptions',
        'text_align' => 'getTextAlign',
        'text_direction' => 'getTextDirection',
        'character_spacing' => 'getCharacterSpacing',
        'background_hex_color' => 'getBackgroundHexColor',
        'tab_index' => 'getTabIndex',
        'formula_field_settings' => 'getFormulaFieldSettings',
        'resize_option' => 'getResizeOption',
        'allow_edit_form_field' => 'getAllowEditFormField',
        'allow_delete_form_field' => 'getAllowDeleteFormField',
        'collaboration_settings' => 'getCollaborationSettings',
        'hidden' => 'getHidden'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const VALIDATIONTYPE_NONE = 'None';
    public const VALIDATIONTYPE_NUMBERS_ONLY = 'NumbersOnly';
    public const VALIDATIONTYPE_EMAIL_ADDRESS = 'EmailAddress';
    public const VALIDATIONTYPE_CURRENCY = 'Currency';
    public const VALIDATIONTYPE_CUSTOM_REGEX = 'CustomRegex';
    public const TEXT_ALIGN_LEFT = 'Left';
    public const TEXT_ALIGN_CENTER = 'Center';
    public const TEXT_ALIGN_RIGHT = 'Right';
    public const TEXT_DIRECTION_LTR = 'LTR';
    public const TEXT_DIRECTION_RTL = 'RTL';
    public const RESIZE_OPTION_GROW_VERTICALLY = 'GrowVertically';
    public const RESIZE_OPTION_GROW_HORIZONTALLY = 'GrowHorizontally';
    public const RESIZE_OPTION_GROW_BOTH = 'GrowBoth';
    public const RESIZE_OPTION_FIXED = 'Fixed';
    public const RESIZE_OPTION_AUTO_RESIZE_FONT = 'AutoResizeFont';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getValidationtypeAllowableValues()
    {
        return [
            self::VALIDATIONTYPE_NONE,
            self::VALIDATIONTYPE_NUMBERS_ONLY,
            self::VALIDATIONTYPE_EMAIL_ADDRESS,
            self::VALIDATIONTYPE_CURRENCY,
            self::VALIDATIONTYPE_CUSTOM_REGEX,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTextAlignAllowableValues()
    {
        return [
            self::TEXT_ALIGN_LEFT,
            self::TEXT_ALIGN_CENTER,
            self::TEXT_ALIGN_RIGHT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTextDirectionAllowableValues()
    {
        return [
            self::TEXT_DIRECTION_LTR,
            self::TEXT_DIRECTION_RTL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getResizeOptionAllowableValues()
    {
        return [
            self::RESIZE_OPTION_GROW_VERTICALLY,
            self::RESIZE_OPTION_GROW_HORIZONTALLY,
            self::RESIZE_OPTION_GROW_BOTH,
            self::RESIZE_OPTION_FIXED,
            self::RESIZE_OPTION_AUTO_RESIZE_FONT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('form_field_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('font', $data ?? [], null);
        $this->setIfExists('is_required', $data ?? [], null);
        $this->setIfExists('is_read_only', $data ?? [], null);
        $this->setIfExists('line_height', $data ?? [], null);
        $this->setIfExists('font_size', $data ?? [], null);
        $this->setIfExists('font_color', $data ?? [], null);
        $this->setIfExists('is_underline', $data ?? [], null);
        $this->setIfExists('is_italic', $data ?? [], null);
        $this->setIfExists('is_bold', $data ?? [], null);
        $this->setIfExists('group_name', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('placeholder', $data ?? [], null);
        $this->setIfExists('validationtype', $data ?? [], null);
        $this->setIfExists('validation_custom_regex', $data ?? [], null);
        $this->setIfExists('validation_custom_regex_message', $data ?? [], null);
        $this->setIfExists('date_format', $data ?? [], null);
        $this->setIfExists('time_format', $data ?? [], null);
        $this->setIfExists('image_info', $data ?? [], null);
        $this->setIfExists('attachment_info', $data ?? [], null);
        $this->setIfExists('file_info', $data ?? [], null);
        $this->setIfExists('editable_date_field_settings', $data ?? [], null);
        $this->setIfExists('hyperlink_text', $data ?? [], null);
        $this->setIfExists('conditional_rules', $data ?? [], null);
        $this->setIfExists('bounds', $data ?? [], null);
        $this->setIfExists('page_number', $data ?? [], null);
        $this->setIfExists('data_sync_tag', $data ?? [], null);
        $this->setIfExists('dropdown_options', $data ?? [], null);
        $this->setIfExists('text_align', $data ?? [], null);
        $this->setIfExists('text_direction', $data ?? [], null);
        $this->setIfExists('character_spacing', $data ?? [], null);
        $this->setIfExists('background_hex_color', $data ?? [], null);
        $this->setIfExists('tab_index', $data ?? [], null);
        $this->setIfExists('formula_field_settings', $data ?? [], null);
        $this->setIfExists('resize_option', $data ?? [], null);
        $this->setIfExists('allow_edit_form_field', $data ?? [], null);
        $this->setIfExists('allow_delete_form_field', $data ?? [], null);
        $this->setIfExists('collaboration_settings', $data ?? [], null);
        $this->setIfExists('hidden', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getValidationtypeAllowableValues();
        if (!is_null($this->container['validationtype']) && !in_array($this->container['validationtype'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'validationtype', must be one of '%s'",
                $this->container['validationtype'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTextAlignAllowableValues();
        if (!is_null($this->container['text_align']) && !in_array($this->container['text_align'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'text_align', must be one of '%s'",
                $this->container['text_align'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTextDirectionAllowableValues();
        if (!is_null($this->container['text_direction']) && !in_array($this->container['text_direction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'text_direction', must be one of '%s'",
                $this->container['text_direction'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getResizeOptionAllowableValues();
        if (!is_null($this->container['resize_option']) && !in_array($this->container['resize_option'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'resize_option', must be one of '%s'",
                $this->container['resize_option'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets form_field_id
     *
     * @return string|null
     */
    public function getFormFieldId()
    {
        return $this->container['form_field_id'];
    }

    /**
     * Sets form_field_id
     *
     * @param string|null $form_field_id form_field_id
     *
     * @return self
     */
    public function setFormFieldId($form_field_id)
    {
        if (is_null($form_field_id)) {
            array_push($this->openAPINullablesSetToNull, 'form_field_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('form_field_id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['form_field_id'] = $form_field_id;

        return $this;
    }

    /**
     * Gets type
     *
     * @return string|null
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param string|null $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            array_push($this->openAPINullablesSetToNull, 'type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['type'] = $type;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string|null $value value
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            array_push($this->openAPINullablesSetToNull, 'value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets font
     *
     * @return string|null
     */
    public function getFont()
    {
        return $this->container['font'];
    }

    /**
     * Sets font
     *
     * @param string|null $font font
     *
     * @return self
     */
    public function setFont($font)
    {
        if (is_null($font)) {
            array_push($this->openAPINullablesSetToNull, 'font');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('font', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['font'] = $font;

        return $this;
    }

    /**
     * Gets is_required
     *
     * @return bool|null
     */
    public function getIsRequired()
    {
        return $this->container['is_required'];
    }

    /**
     * Sets is_required
     *
     * @param bool|null $is_required is_required
     *
     * @return self
     */
    public function setIsRequired($is_required)
    {
        if (is_null($is_required)) {
            throw new \InvalidArgumentException('non-nullable is_required cannot be null');
        }
        $this->container['is_required'] = $is_required;

        return $this;
    }

    /**
     * Gets is_read_only
     *
     * @return bool|null
     */
    public function getIsReadOnly()
    {
        return $this->container['is_read_only'];
    }

    /**
     * Sets is_read_only
     *
     * @param bool|null $is_read_only is_read_only
     *
     * @return self
     */
    public function setIsReadOnly($is_read_only)
    {
        if (is_null($is_read_only)) {
            throw new \InvalidArgumentException('non-nullable is_read_only cannot be null');
        }
        $this->container['is_read_only'] = $is_read_only;

        return $this;
    }

    /**
     * Gets line_height
     *
     * @return float|null
     */
    public function getLineHeight()
    {
        return $this->container['line_height'];
    }

    /**
     * Sets line_height
     *
     * @param float|null $line_height line_height
     *
     * @return self
     */
    public function setLineHeight($line_height)
    {
        if (is_null($line_height)) {
            throw new \InvalidArgumentException('non-nullable line_height cannot be null');
        }
        $this->container['line_height'] = $line_height;

        return $this;
    }

    /**
     * Gets font_size
     *
     * @return float|null
     */
    public function getFontSize()
    {
        return $this->container['font_size'];
    }

    /**
     * Sets font_size
     *
     * @param float|null $font_size font_size
     *
     * @return self
     */
    public function setFontSize($font_size)
    {
        if (is_null($font_size)) {
            throw new \InvalidArgumentException('non-nullable font_size cannot be null');
        }
        $this->container['font_size'] = $font_size;

        return $this;
    }

    /**
     * Gets font_color
     *
     * @return string|null
     */
    public function getFontColor()
    {
        return $this->container['font_color'];
    }

    /**
     * Sets font_color
     *
     * @param string|null $font_color font_color
     *
     * @return self
     */
    public function setFontColor($font_color)
    {
        if (is_null($font_color)) {
            array_push($this->openAPINullablesSetToNull, 'font_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('font_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['font_color'] = $font_color;

        return $this;
    }

    /**
     * Gets is_underline
     *
     * @return bool|null
     */
    public function getIsUnderline()
    {
        return $this->container['is_underline'];
    }

    /**
     * Sets is_underline
     *
     * @param bool|null $is_underline is_underline
     *
     * @return self
     */
    public function setIsUnderline($is_underline)
    {
        if (is_null($is_underline)) {
            throw new \InvalidArgumentException('non-nullable is_underline cannot be null');
        }
        $this->container['is_underline'] = $is_underline;

        return $this;
    }

    /**
     * Gets is_italic
     *
     * @return bool|null
     */
    public function getIsItalic()
    {
        return $this->container['is_italic'];
    }

    /**
     * Sets is_italic
     *
     * @param bool|null $is_italic is_italic
     *
     * @return self
     */
    public function setIsItalic($is_italic)
    {
        if (is_null($is_italic)) {
            throw new \InvalidArgumentException('non-nullable is_italic cannot be null');
        }
        $this->container['is_italic'] = $is_italic;

        return $this;
    }

    /**
     * Gets is_bold
     *
     * @return bool|null
     */
    public function getIsBold()
    {
        return $this->container['is_bold'];
    }

    /**
     * Sets is_bold
     *
     * @param bool|null $is_bold is_bold
     *
     * @return self
     */
    public function setIsBold($is_bold)
    {
        if (is_null($is_bold)) {
            throw new \InvalidArgumentException('non-nullable is_bold cannot be null');
        }
        $this->container['is_bold'] = $is_bold;

        return $this;
    }

    /**
     * Gets group_name
     *
     * @return string|null
     */
    public function getGroupName()
    {
        return $this->container['group_name'];
    }

    /**
     * Sets group_name
     *
     * @param string|null $group_name group_name
     *
     * @return self
     */
    public function setGroupName($group_name)
    {
        if (is_null($group_name)) {
            array_push($this->openAPINullablesSetToNull, 'group_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group_name'] = $group_name;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            array_push($this->openAPINullablesSetToNull, 'label');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('label', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets placeholder
     *
     * @return string|null
     */
    public function getPlaceholder()
    {
        return $this->container['placeholder'];
    }

    /**
     * Sets placeholder
     *
     * @param string|null $placeholder placeholder
     *
     * @return self
     */
    public function setPlaceholder($placeholder)
    {
        if (is_null($placeholder)) {
            array_push($this->openAPINullablesSetToNull, 'placeholder');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('placeholder', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['placeholder'] = $placeholder;

        return $this;
    }

    /**
     * Gets validationtype
     *
     * @return string|null
     */
    public function getValidationtype()
    {
        return $this->container['validationtype'];
    }

    /**
     * Sets validationtype
     *
     * @param string|null $validationtype validationtype
     *
     * @return self
     */
    public function setValidationtype($validationtype)
    {
        if (is_null($validationtype)) {
            throw new \InvalidArgumentException('non-nullable validationtype cannot be null');
        }
        $allowedValues = $this->getValidationtypeAllowableValues();
        if (!in_array($validationtype, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'validationtype', must be one of '%s'",
                    $validationtype,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['validationtype'] = $validationtype;

        return $this;
    }

    /**
     * Gets validation_custom_regex
     *
     * @return string|null
     */
    public function getValidationCustomRegex()
    {
        return $this->container['validation_custom_regex'];
    }

    /**
     * Sets validation_custom_regex
     *
     * @param string|null $validation_custom_regex validation_custom_regex
     *
     * @return self
     */
    public function setValidationCustomRegex($validation_custom_regex)
    {
        if (is_null($validation_custom_regex)) {
            array_push($this->openAPINullablesSetToNull, 'validation_custom_regex');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validation_custom_regex', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validation_custom_regex'] = $validation_custom_regex;

        return $this;
    }

    /**
     * Gets validation_custom_regex_message
     *
     * @return string|null
     */
    public function getValidationCustomRegexMessage()
    {
        return $this->container['validation_custom_regex_message'];
    }

    /**
     * Sets validation_custom_regex_message
     *
     * @param string|null $validation_custom_regex_message validation_custom_regex_message
     *
     * @return self
     */
    public function setValidationCustomRegexMessage($validation_custom_regex_message)
    {
        if (is_null($validation_custom_regex_message)) {
            array_push($this->openAPINullablesSetToNull, 'validation_custom_regex_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validation_custom_regex_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validation_custom_regex_message'] = $validation_custom_regex_message;

        return $this;
    }

    /**
     * Gets date_format
     *
     * @return string|null
     */
    public function getDateFormat()
    {
        return $this->container['date_format'];
    }

    /**
     * Sets date_format
     *
     * @param string|null $date_format date_format
     *
     * @return self
     */
    public function setDateFormat($date_format)
    {
        if (is_null($date_format)) {
            array_push($this->openAPINullablesSetToNull, 'date_format');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_format', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_format'] = $date_format;

        return $this;
    }

    /**
     * Gets time_format
     *
     * @return string|null
     */
    public function getTimeFormat()
    {
        return $this->container['time_format'];
    }

    /**
     * Sets time_format
     *
     * @param string|null $time_format time_format
     *
     * @return self
     */
    public function setTimeFormat($time_format)
    {
        if (is_null($time_format)) {
            array_push($this->openAPINullablesSetToNull, 'time_format');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time_format', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['time_format'] = $time_format;

        return $this;
    }

    /**
     * Gets image_info
     *
     * @return \BoldSign\Model\ImageInfo|null
     */
    public function getImageInfo()
    {
        return $this->container['image_info'];
    }

    /**
     * Sets image_info
     *
     * @param \BoldSign\Model\ImageInfo|null $image_info image_info
     *
     * @return self
     */
    public function setImageInfo($image_info)
    {
        if (is_null($image_info)) {
            throw new \InvalidArgumentException('non-nullable image_info cannot be null');
        }
        $this->container['image_info'] = $image_info;

        return $this;
    }

    /**
     * Gets attachment_info
     *
     * @return \BoldSign\Model\AttachmentInfo|null
     */
    public function getAttachmentInfo()
    {
        return $this->container['attachment_info'];
    }

    /**
     * Sets attachment_info
     *
     * @param \BoldSign\Model\AttachmentInfo|null $attachment_info attachment_info
     *
     * @return self
     */
    public function setAttachmentInfo($attachment_info)
    {
        if (is_null($attachment_info)) {
            throw new \InvalidArgumentException('non-nullable attachment_info cannot be null');
        }
        $this->container['attachment_info'] = $attachment_info;

        return $this;
    }

    /**
     * Gets file_info
     *
     * @return \BoldSign\Model\FileInfo|null
     */
    public function getFileInfo()
    {
        return $this->container['file_info'];
    }

    /**
     * Sets file_info
     *
     * @param \BoldSign\Model\FileInfo|null $file_info file_info
     *
     * @return self
     */
    public function setFileInfo($file_info)
    {
        if (is_null($file_info)) {
            throw new \InvalidArgumentException('non-nullable file_info cannot be null');
        }
        $this->container['file_info'] = $file_info;

        return $this;
    }

    /**
     * Gets editable_date_field_settings
     *
     * @return \BoldSign\Model\EditableDateFieldSettings|null
     */
    public function getEditableDateFieldSettings()
    {
        return $this->container['editable_date_field_settings'];
    }

    /**
     * Sets editable_date_field_settings
     *
     * @param \BoldSign\Model\EditableDateFieldSettings|null $editable_date_field_settings editable_date_field_settings
     *
     * @return self
     */
    public function setEditableDateFieldSettings($editable_date_field_settings)
    {
        if (is_null($editable_date_field_settings)) {
            throw new \InvalidArgumentException('non-nullable editable_date_field_settings cannot be null');
        }
        $this->container['editable_date_field_settings'] = $editable_date_field_settings;

        return $this;
    }

    /**
     * Gets hyperlink_text
     *
     * @return string|null
     */
    public function getHyperlinkText()
    {
        return $this->container['hyperlink_text'];
    }

    /**
     * Sets hyperlink_text
     *
     * @param string|null $hyperlink_text hyperlink_text
     *
     * @return self
     */
    public function setHyperlinkText($hyperlink_text)
    {
        if (is_null($hyperlink_text)) {
            array_push($this->openAPINullablesSetToNull, 'hyperlink_text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hyperlink_text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hyperlink_text'] = $hyperlink_text;

        return $this;
    }

    /**
     * Gets conditional_rules
     *
     * @return \BoldSign\Model\ConditionalRule[]|null
     */
    public function getConditionalRules()
    {
        return $this->container['conditional_rules'];
    }

    /**
     * Sets conditional_rules
     *
     * @param \BoldSign\Model\ConditionalRule[]|null $conditional_rules conditional_rules
     *
     * @return self
     */
    public function setConditionalRules($conditional_rules)
    {
        if (is_null($conditional_rules)) {
            array_push($this->openAPINullablesSetToNull, 'conditional_rules');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('conditional_rules', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['conditional_rules'] = $conditional_rules;

        return $this;
    }

    /**
     * Gets bounds
     *
     * @return \BoldSign\Model\Rectangle|null
     */
    public function getBounds()
    {
        return $this->container['bounds'];
    }

    /**
     * Sets bounds
     *
     * @param \BoldSign\Model\Rectangle|null $bounds bounds
     *
     * @return self
     */
    public function setBounds($bounds)
    {
        if (is_null($bounds)) {
            throw new \InvalidArgumentException('non-nullable bounds cannot be null');
        }
        $this->container['bounds'] = $bounds;

        return $this;
    }

    /**
     * Gets page_number
     *
     * @return int|null
     */
    public function getPageNumber()
    {
        return $this->container['page_number'];
    }

    /**
     * Sets page_number
     *
     * @param int|null $page_number page_number
     *
     * @return self
     */
    public function setPageNumber($page_number)
    {
        if (is_null($page_number)) {
            throw new \InvalidArgumentException('non-nullable page_number cannot be null');
        }
        $this->container['page_number'] = $page_number;

        return $this;
    }

    /**
     * Gets data_sync_tag
     *
     * @return string|null
     */
    public function getDataSyncTag()
    {
        return $this->container['data_sync_tag'];
    }

    /**
     * Sets data_sync_tag
     *
     * @param string|null $data_sync_tag data_sync_tag
     *
     * @return self
     */
    public function setDataSyncTag($data_sync_tag)
    {
        if (is_null($data_sync_tag)) {
            array_push($this->openAPINullablesSetToNull, 'data_sync_tag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_sync_tag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_sync_tag'] = $data_sync_tag;

        return $this;
    }

    /**
     * Gets dropdown_options
     *
     * @return string[]|null
     */
    public function getDropdownOptions()
    {
        return $this->container['dropdown_options'];
    }

    /**
     * Sets dropdown_options
     *
     * @param string[]|null $dropdown_options dropdown_options
     *
     * @return self
     */
    public function setDropdownOptions($dropdown_options)
    {
        if (is_null($dropdown_options)) {
            array_push($this->openAPINullablesSetToNull, 'dropdown_options');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dropdown_options', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dropdown_options'] = $dropdown_options;

        return $this;
    }

    /**
     * Gets text_align
     *
     * @return string|null
     */
    public function getTextAlign()
    {
        return $this->container['text_align'];
    }

    /**
     * Sets text_align
     *
     * @param string|null $text_align text_align
     *
     * @return self
     */
    public function setTextAlign($text_align)
    {
        if (is_null($text_align)) {
            throw new \InvalidArgumentException('non-nullable text_align cannot be null');
        }
        $allowedValues = $this->getTextAlignAllowableValues();
        if (!in_array($text_align, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'text_align', must be one of '%s'",
                    $text_align,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['text_align'] = $text_align;

        return $this;
    }

    /**
     * Gets text_direction
     *
     * @return string|null
     */
    public function getTextDirection()
    {
        return $this->container['text_direction'];
    }

    /**
     * Sets text_direction
     *
     * @param string|null $text_direction text_direction
     *
     * @return self
     */
    public function setTextDirection($text_direction)
    {
        if (is_null($text_direction)) {
            throw new \InvalidArgumentException('non-nullable text_direction cannot be null');
        }
        $allowedValues = $this->getTextDirectionAllowableValues();
        if (!in_array($text_direction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'text_direction', must be one of '%s'",
                    $text_direction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['text_direction'] = $text_direction;

        return $this;
    }

    /**
     * Gets character_spacing
     *
     * @return float|null
     */
    public function getCharacterSpacing()
    {
        return $this->container['character_spacing'];
    }

    /**
     * Sets character_spacing
     *
     * @param float|null $character_spacing character_spacing
     *
     * @return self
     */
    public function setCharacterSpacing($character_spacing)
    {
        if (is_null($character_spacing)) {
            throw new \InvalidArgumentException('non-nullable character_spacing cannot be null');
        }
        $this->container['character_spacing'] = $character_spacing;

        return $this;
    }

    /**
     * Gets background_hex_color
     *
     * @return string|null
     */
    public function getBackgroundHexColor()
    {
        return $this->container['background_hex_color'];
    }

    /**
     * Sets background_hex_color
     *
     * @param string|null $background_hex_color background_hex_color
     *
     * @return self
     */
    public function setBackgroundHexColor($background_hex_color)
    {
        if (is_null($background_hex_color)) {
            array_push($this->openAPINullablesSetToNull, 'background_hex_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('background_hex_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['background_hex_color'] = $background_hex_color;

        return $this;
    }

    /**
     * Gets tab_index
     *
     * @return int|null
     */
    public function getTabIndex()
    {
        return $this->container['tab_index'];
    }

    /**
     * Sets tab_index
     *
     * @param int|null $tab_index tab_index
     *
     * @return self
     */
    public function setTabIndex($tab_index)
    {
        if (is_null($tab_index)) {
            throw new \InvalidArgumentException('non-nullable tab_index cannot be null');
        }
        $this->container['tab_index'] = $tab_index;

        return $this;
    }

    /**
     * Gets formula_field_settings
     *
     * @return \BoldSign\Model\FormulaFieldSettings|null
     */
    public function getFormulaFieldSettings()
    {
        return $this->container['formula_field_settings'];
    }

    /**
     * Sets formula_field_settings
     *
     * @param \BoldSign\Model\FormulaFieldSettings|null $formula_field_settings formula_field_settings
     *
     * @return self
     */
    public function setFormulaFieldSettings($formula_field_settings)
    {
        if (is_null($formula_field_settings)) {
            throw new \InvalidArgumentException('non-nullable formula_field_settings cannot be null');
        }
        $this->container['formula_field_settings'] = $formula_field_settings;

        return $this;
    }

    /**
     * Gets resize_option
     *
     * @return string|null
     */
    public function getResizeOption()
    {
        return $this->container['resize_option'];
    }

    /**
     * Sets resize_option
     *
     * @param string|null $resize_option resize_option
     *
     * @return self
     */
    public function setResizeOption($resize_option)
    {
        if (is_null($resize_option)) {
            array_push($this->openAPINullablesSetToNull, 'resize_option');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resize_option', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getResizeOptionAllowableValues();
        if (!is_null($resize_option) && !in_array($resize_option, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'resize_option', must be one of '%s'",
                    $resize_option,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['resize_option'] = $resize_option;

        return $this;
    }

    /**
     * Gets allow_edit_form_field
     *
     * @return bool|null
     */
    public function getAllowEditFormField()
    {
        return $this->container['allow_edit_form_field'];
    }

    /**
     * Sets allow_edit_form_field
     *
     * @param bool|null $allow_edit_form_field allow_edit_form_field
     *
     * @return self
     */
    public function setAllowEditFormField($allow_edit_form_field)
    {
        if (is_null($allow_edit_form_field)) {
            throw new \InvalidArgumentException('non-nullable allow_edit_form_field cannot be null');
        }
        $this->container['allow_edit_form_field'] = $allow_edit_form_field;

        return $this;
    }

    /**
     * Gets allow_delete_form_field
     *
     * @return bool|null
     */
    public function getAllowDeleteFormField()
    {
        return $this->container['allow_delete_form_field'];
    }

    /**
     * Sets allow_delete_form_field
     *
     * @param bool|null $allow_delete_form_field allow_delete_form_field
     *
     * @return self
     */
    public function setAllowDeleteFormField($allow_delete_form_field)
    {
        if (is_null($allow_delete_form_field)) {
            throw new \InvalidArgumentException('non-nullable allow_delete_form_field cannot be null');
        }
        $this->container['allow_delete_form_field'] = $allow_delete_form_field;

        return $this;
    }

    /**
     * Gets collaboration_settings
     *
     * @return \BoldSign\Model\CollaborationSettings|null
     */
    public function getCollaborationSettings()
    {
        return $this->container['collaboration_settings'];
    }

    /**
     * Sets collaboration_settings
     *
     * @param \BoldSign\Model\CollaborationSettings|null $collaboration_settings collaboration_settings
     *
     * @return self
     */
    public function setCollaborationSettings($collaboration_settings)
    {
        if (is_null($collaboration_settings)) {
            throw new \InvalidArgumentException('non-nullable collaboration_settings cannot be null');
        }
        $this->container['collaboration_settings'] = $collaboration_settings;

        return $this;
    }

    /**
     * Gets hidden
     *
     * @return bool|null
     */
    public function getHidden()
    {
        return $this->container['hidden'];
    }

    /**
     * Sets hidden
     *
     * @param bool|null $hidden hidden
     *
     * @return self
     */
    public function setHidden($hidden)
    {
        if (is_null($hidden)) {
            throw new \InvalidArgumentException('non-nullable hidden cannot be null');
        }
        $this->container['hidden'] = $hidden;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


