<?php
/**
 * FormField
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BoldSign\Model;

use \ArrayAccess;
use \BoldSign\ObjectSerializer;

/**
 * FormField Class Doc Comment
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FormField implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'FormField';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'field_type' => 'string',
        'page_number' => 'int',
        'bounds' => '\BoldSign\Model\Rectangle',
        'id' => 'string',
        'name' => 'string',
        'is_required' => 'bool',
        'is_read_only' => 'bool',
        'value' => 'string',
        'font_size' => 'float',
        'font' => 'string',
        'font_hex_color' => 'string',
        'is_bold_font' => 'bool',
        'is_italic_font' => 'bool',
        'is_under_line_font' => 'bool',
        'line_height' => 'int',
        'character_limit' => 'int',
        'group_name' => 'string',
        'label' => 'string',
        'place_holder' => 'string',
        'validation_type' => 'string',
        'validation_custom_regex' => 'string',
        'validation_custom_regex_message' => 'string',
        'date_format' => 'string',
        'time_format' => 'string',
        'image_info' => '\BoldSign\Model\ImageInfo',
        'attachment_info' => '\BoldSign\Model\AttachmentInfo',
        'editable_date_field_settings' => '\BoldSign\Model\EditableDateFieldSettings',
        'hyperlink_text' => 'string',
        'conditional_rules' => '\BoldSign\Model\ConditionalRule[]',
        'data_sync_tag' => 'string',
        'dropdown_options' => 'string[]',
        'text_align' => 'string',
        'text_direction' => 'string',
        'character_spacing' => 'float',
        'background_hex_color' => 'string',
        'tab_index' => 'int',
        'formula_field_settings' => '\BoldSign\Model\FormulaFieldSettings',
        'resize_option' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'field_type' => null,
        'page_number' => 'int32',
        'bounds' => null,
        'id' => null,
        'name' => null,
        'is_required' => null,
        'is_read_only' => null,
        'value' => null,
        'font_size' => 'float',
        'font' => null,
        'font_hex_color' => null,
        'is_bold_font' => null,
        'is_italic_font' => null,
        'is_under_line_font' => null,
        'line_height' => 'int32',
        'character_limit' => 'int32',
        'group_name' => null,
        'label' => null,
        'place_holder' => null,
        'validation_type' => null,
        'validation_custom_regex' => null,
        'validation_custom_regex_message' => null,
        'date_format' => null,
        'time_format' => null,
        'image_info' => null,
        'attachment_info' => null,
        'editable_date_field_settings' => null,
        'hyperlink_text' => null,
        'conditional_rules' => null,
        'data_sync_tag' => null,
        'dropdown_options' => null,
        'text_align' => null,
        'text_direction' => null,
        'character_spacing' => 'float',
        'background_hex_color' => null,
        'tab_index' => 'int32',
        'formula_field_settings' => null,
        'resize_option' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'field_type' => false,
        'page_number' => false,
        'bounds' => false,
        'id' => true,
        'name' => true,
        'is_required' => false,
        'is_read_only' => false,
        'value' => true,
        'font_size' => false,
        'font' => false,
        'font_hex_color' => true,
        'is_bold_font' => false,
        'is_italic_font' => false,
        'is_under_line_font' => false,
        'line_height' => false,
        'character_limit' => false,
        'group_name' => true,
        'label' => true,
        'place_holder' => true,
        'validation_type' => false,
        'validation_custom_regex' => true,
        'validation_custom_regex_message' => true,
        'date_format' => true,
        'time_format' => true,
        'image_info' => false,
        'attachment_info' => false,
        'editable_date_field_settings' => false,
        'hyperlink_text' => true,
        'conditional_rules' => true,
        'data_sync_tag' => true,
        'dropdown_options' => true,
        'text_align' => false,
        'text_direction' => false,
        'character_spacing' => false,
        'background_hex_color' => true,
        'tab_index' => true,
        'formula_field_settings' => false,
        'resize_option' => true
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'field_type' => 'fieldType',
        'page_number' => 'pageNumber',
        'bounds' => 'bounds',
        'id' => 'id',
        'name' => 'name',
        'is_required' => 'isRequired',
        'is_read_only' => 'isReadOnly',
        'value' => 'value',
        'font_size' => 'fontSize',
        'font' => 'font',
        'font_hex_color' => 'fontHexColor',
        'is_bold_font' => 'isBoldFont',
        'is_italic_font' => 'isItalicFont',
        'is_under_line_font' => 'isUnderLineFont',
        'line_height' => 'lineHeight',
        'character_limit' => 'characterLimit',
        'group_name' => 'groupName',
        'label' => 'label',
        'place_holder' => 'placeHolder',
        'validation_type' => 'validationType',
        'validation_custom_regex' => 'validationCustomRegex',
        'validation_custom_regex_message' => 'validationCustomRegexMessage',
        'date_format' => 'dateFormat',
        'time_format' => 'timeFormat',
        'image_info' => 'imageInfo',
        'attachment_info' => 'attachmentInfo',
        'editable_date_field_settings' => 'editableDateFieldSettings',
        'hyperlink_text' => 'hyperlinkText',
        'conditional_rules' => 'conditionalRules',
        'data_sync_tag' => 'dataSyncTag',
        'dropdown_options' => 'dropdownOptions',
        'text_align' => 'textAlign',
        'text_direction' => 'textDirection',
        'character_spacing' => 'characterSpacing',
        'background_hex_color' => 'backgroundHexColor',
        'tab_index' => 'tabIndex',
        'formula_field_settings' => 'formulaFieldSettings',
        'resize_option' => 'resizeOption'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'field_type' => 'setFieldType',
        'page_number' => 'setPageNumber',
        'bounds' => 'setBounds',
        'id' => 'setId',
        'name' => 'setName',
        'is_required' => 'setIsRequired',
        'is_read_only' => 'setIsReadOnly',
        'value' => 'setValue',
        'font_size' => 'setFontSize',
        'font' => 'setFont',
        'font_hex_color' => 'setFontHexColor',
        'is_bold_font' => 'setIsBoldFont',
        'is_italic_font' => 'setIsItalicFont',
        'is_under_line_font' => 'setIsUnderLineFont',
        'line_height' => 'setLineHeight',
        'character_limit' => 'setCharacterLimit',
        'group_name' => 'setGroupName',
        'label' => 'setLabel',
        'place_holder' => 'setPlaceHolder',
        'validation_type' => 'setValidationType',
        'validation_custom_regex' => 'setValidationCustomRegex',
        'validation_custom_regex_message' => 'setValidationCustomRegexMessage',
        'date_format' => 'setDateFormat',
        'time_format' => 'setTimeFormat',
        'image_info' => 'setImageInfo',
        'attachment_info' => 'setAttachmentInfo',
        'editable_date_field_settings' => 'setEditableDateFieldSettings',
        'hyperlink_text' => 'setHyperlinkText',
        'conditional_rules' => 'setConditionalRules',
        'data_sync_tag' => 'setDataSyncTag',
        'dropdown_options' => 'setDropdownOptions',
        'text_align' => 'setTextAlign',
        'text_direction' => 'setTextDirection',
        'character_spacing' => 'setCharacterSpacing',
        'background_hex_color' => 'setBackgroundHexColor',
        'tab_index' => 'setTabIndex',
        'formula_field_settings' => 'setFormulaFieldSettings',
        'resize_option' => 'setResizeOption'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'field_type' => 'getFieldType',
        'page_number' => 'getPageNumber',
        'bounds' => 'getBounds',
        'id' => 'getId',
        'name' => 'getName',
        'is_required' => 'getIsRequired',
        'is_read_only' => 'getIsReadOnly',
        'value' => 'getValue',
        'font_size' => 'getFontSize',
        'font' => 'getFont',
        'font_hex_color' => 'getFontHexColor',
        'is_bold_font' => 'getIsBoldFont',
        'is_italic_font' => 'getIsItalicFont',
        'is_under_line_font' => 'getIsUnderLineFont',
        'line_height' => 'getLineHeight',
        'character_limit' => 'getCharacterLimit',
        'group_name' => 'getGroupName',
        'label' => 'getLabel',
        'place_holder' => 'getPlaceHolder',
        'validation_type' => 'getValidationType',
        'validation_custom_regex' => 'getValidationCustomRegex',
        'validation_custom_regex_message' => 'getValidationCustomRegexMessage',
        'date_format' => 'getDateFormat',
        'time_format' => 'getTimeFormat',
        'image_info' => 'getImageInfo',
        'attachment_info' => 'getAttachmentInfo',
        'editable_date_field_settings' => 'getEditableDateFieldSettings',
        'hyperlink_text' => 'getHyperlinkText',
        'conditional_rules' => 'getConditionalRules',
        'data_sync_tag' => 'getDataSyncTag',
        'dropdown_options' => 'getDropdownOptions',
        'text_align' => 'getTextAlign',
        'text_direction' => 'getTextDirection',
        'character_spacing' => 'getCharacterSpacing',
        'background_hex_color' => 'getBackgroundHexColor',
        'tab_index' => 'getTabIndex',
        'formula_field_settings' => 'getFormulaFieldSettings',
        'resize_option' => 'getResizeOption'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const FIELD_TYPE_SIGNATURE = 'Signature';
    public const FIELD_TYPE_INITIAL = 'Initial';
    public const FIELD_TYPE_CHECK_BOX = 'CheckBox';
    public const FIELD_TYPE_TEXT_BOX = 'TextBox';
    public const FIELD_TYPE_LABEL = 'Label';
    public const FIELD_TYPE_DATE_SIGNED = 'DateSigned';
    public const FIELD_TYPE_RADIO_BUTTON = 'RadioButton';
    public const FIELD_TYPE_IMAGE = 'Image';
    public const FIELD_TYPE_ATTACHMENT = 'Attachment';
    public const FIELD_TYPE_EDITABLE_DATE = 'EditableDate';
    public const FIELD_TYPE_HYPERLINK = 'Hyperlink';
    public const FIELD_TYPE_DROPDOWN = 'Dropdown';
    public const FIELD_TYPE_TITLE = 'Title';
    public const FIELD_TYPE_COMPANY = 'Company';
    public const FIELD_TYPE_FORMULA = 'Formula';
    public const FONT_HELVETICA = 'Helvetica';
    public const FONT_COURIER = 'Courier';
    public const FONT_TIMES_ROMAN = 'TimesRoman';
    public const FONT_NOTO_SANS = 'NotoSans';
    public const VALIDATION_TYPE_NONE = 'None';
    public const VALIDATION_TYPE_NUMBERS_ONLY = 'NumbersOnly';
    public const VALIDATION_TYPE_EMAIL_ADDRESS = 'EmailAddress';
    public const VALIDATION_TYPE_CURRENCY = 'Currency';
    public const VALIDATION_TYPE_CUSTOM_REGEX = 'CustomRegex';
    public const TEXT_ALIGN_LEFT = 'Left';
    public const TEXT_ALIGN_CENTER = 'Center';
    public const TEXT_ALIGN_RIGHT = 'Right';
    public const TEXT_DIRECTION_LTR = 'LTR';
    public const TEXT_DIRECTION_RTL = 'RTL';
    public const RESIZE_OPTION_GROW_VERTICALLY = 'GrowVertically';
    public const RESIZE_OPTION_GROW_HORIZONTALLY = 'GrowHorizontally';
    public const RESIZE_OPTION_GROW_BOTH = 'GrowBoth';
    public const RESIZE_OPTION_FIXED = 'Fixed';
    public const RESIZE_OPTION_AUTO_RESIZE_FONT = 'AutoResizeFont';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFieldTypeAllowableValues()
    {
        return [
            self::FIELD_TYPE_SIGNATURE,
            self::FIELD_TYPE_INITIAL,
            self::FIELD_TYPE_CHECK_BOX,
            self::FIELD_TYPE_TEXT_BOX,
            self::FIELD_TYPE_LABEL,
            self::FIELD_TYPE_DATE_SIGNED,
            self::FIELD_TYPE_RADIO_BUTTON,
            self::FIELD_TYPE_IMAGE,
            self::FIELD_TYPE_ATTACHMENT,
            self::FIELD_TYPE_EDITABLE_DATE,
            self::FIELD_TYPE_HYPERLINK,
            self::FIELD_TYPE_DROPDOWN,
            self::FIELD_TYPE_TITLE,
            self::FIELD_TYPE_COMPANY,
            self::FIELD_TYPE_FORMULA,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getFontAllowableValues()
    {
        return [
            self::FONT_HELVETICA,
            self::FONT_COURIER,
            self::FONT_TIMES_ROMAN,
            self::FONT_NOTO_SANS,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getValidationTypeAllowableValues()
    {
        return [
            self::VALIDATION_TYPE_NONE,
            self::VALIDATION_TYPE_NUMBERS_ONLY,
            self::VALIDATION_TYPE_EMAIL_ADDRESS,
            self::VALIDATION_TYPE_CURRENCY,
            self::VALIDATION_TYPE_CUSTOM_REGEX,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTextAlignAllowableValues()
    {
        return [
            self::TEXT_ALIGN_LEFT,
            self::TEXT_ALIGN_CENTER,
            self::TEXT_ALIGN_RIGHT,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getTextDirectionAllowableValues()
    {
        return [
            self::TEXT_DIRECTION_LTR,
            self::TEXT_DIRECTION_RTL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getResizeOptionAllowableValues()
    {
        return [
            self::RESIZE_OPTION_GROW_VERTICALLY,
            self::RESIZE_OPTION_GROW_HORIZONTALLY,
            self::RESIZE_OPTION_GROW_BOTH,
            self::RESIZE_OPTION_FIXED,
            self::RESIZE_OPTION_AUTO_RESIZE_FONT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('field_type', $data ?? [], null);
        $this->setIfExists('page_number', $data ?? [], null);
        $this->setIfExists('bounds', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('is_required', $data ?? [], null);
        $this->setIfExists('is_read_only', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('font_size', $data ?? [], null);
        $this->setIfExists('font', $data ?? [], null);
        $this->setIfExists('font_hex_color', $data ?? [], null);
        $this->setIfExists('is_bold_font', $data ?? [], null);
        $this->setIfExists('is_italic_font', $data ?? [], null);
        $this->setIfExists('is_under_line_font', $data ?? [], null);
        $this->setIfExists('line_height', $data ?? [], null);
        $this->setIfExists('character_limit', $data ?? [], null);
        $this->setIfExists('group_name', $data ?? [], null);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('place_holder', $data ?? [], null);
        $this->setIfExists('validation_type', $data ?? [], null);
        $this->setIfExists('validation_custom_regex', $data ?? [], null);
        $this->setIfExists('validation_custom_regex_message', $data ?? [], null);
        $this->setIfExists('date_format', $data ?? [], null);
        $this->setIfExists('time_format', $data ?? [], null);
        $this->setIfExists('image_info', $data ?? [], null);
        $this->setIfExists('attachment_info', $data ?? [], null);
        $this->setIfExists('editable_date_field_settings', $data ?? [], null);
        $this->setIfExists('hyperlink_text', $data ?? [], null);
        $this->setIfExists('conditional_rules', $data ?? [], null);
        $this->setIfExists('data_sync_tag', $data ?? [], null);
        $this->setIfExists('dropdown_options', $data ?? [], null);
        $this->setIfExists('text_align', $data ?? [], null);
        $this->setIfExists('text_direction', $data ?? [], null);
        $this->setIfExists('character_spacing', $data ?? [], null);
        $this->setIfExists('background_hex_color', $data ?? [], null);
        $this->setIfExists('tab_index', $data ?? [], null);
        $this->setIfExists('formula_field_settings', $data ?? [], null);
        $this->setIfExists('resize_option', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['field_type'] === null) {
            $invalidProperties[] = "'field_type' can't be null";
        }
        $allowedValues = $this->getFieldTypeAllowableValues();
        if (!is_null($this->container['field_type']) && !in_array($this->container['field_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'field_type', must be one of '%s'",
                $this->container['field_type'],
                implode("', '", $allowedValues)
            );
        }

        if ($this->container['page_number'] === null) {
            $invalidProperties[] = "'page_number' can't be null";
        }
        if ($this->container['bounds'] === null) {
            $invalidProperties[] = "'bounds' can't be null";
        }
        if (!is_null($this->container['font_size']) && ($this->container['font_size'] < 0)) {
            $invalidProperties[] = "invalid value for 'font_size', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getFontAllowableValues();
        if (!is_null($this->container['font']) && !in_array($this->container['font'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'font', must be one of '%s'",
                $this->container['font'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['line_height']) && ($this->container['line_height'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'line_height', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['line_height']) && ($this->container['line_height'] < 0)) {
            $invalidProperties[] = "invalid value for 'line_height', must be bigger than or equal to 0.";
        }

        if (!is_null($this->container['character_limit']) && ($this->container['character_limit'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'character_limit', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['character_limit']) && ($this->container['character_limit'] < 0)) {
            $invalidProperties[] = "invalid value for 'character_limit', must be bigger than or equal to 0.";
        }

        $allowedValues = $this->getValidationTypeAllowableValues();
        if (!is_null($this->container['validation_type']) && !in_array($this->container['validation_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'validation_type', must be one of '%s'",
                $this->container['validation_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTextAlignAllowableValues();
        if (!is_null($this->container['text_align']) && !in_array($this->container['text_align'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'text_align', must be one of '%s'",
                $this->container['text_align'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getTextDirectionAllowableValues();
        if (!is_null($this->container['text_direction']) && !in_array($this->container['text_direction'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'text_direction', must be one of '%s'",
                $this->container['text_direction'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['tab_index']) && ($this->container['tab_index'] > 2147483647)) {
            $invalidProperties[] = "invalid value for 'tab_index', must be smaller than or equal to 2147483647.";
        }

        if (!is_null($this->container['tab_index']) && ($this->container['tab_index'] < -1)) {
            $invalidProperties[] = "invalid value for 'tab_index', must be bigger than or equal to -1.";
        }

        $allowedValues = $this->getResizeOptionAllowableValues();
        if (!is_null($this->container['resize_option']) && !in_array($this->container['resize_option'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'resize_option', must be one of '%s'",
                $this->container['resize_option'],
                implode("', '", $allowedValues)
            );
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets field_type
     *
     * @return string
     */
    public function getFieldType()
    {
        return $this->container['field_type'];
    }

    /**
     * Sets field_type
     *
     * @param string $field_type field_type
     *
     * @return self
     */
    public function setFieldType($field_type)
    {
        if (is_null($field_type)) {
            throw new \InvalidArgumentException('non-nullable field_type cannot be null');
        }
        $allowedValues = $this->getFieldTypeAllowableValues();
        if (!in_array($field_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'field_type', must be one of '%s'",
                    $field_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['field_type'] = $field_type;

        return $this;
    }

    /**
     * Gets page_number
     *
     * @return int
     */
    public function getPageNumber()
    {
        return $this->container['page_number'];
    }

    /**
     * Sets page_number
     *
     * @param int $page_number page_number
     *
     * @return self
     */
    public function setPageNumber($page_number)
    {
        if (is_null($page_number)) {
            throw new \InvalidArgumentException('non-nullable page_number cannot be null');
        }
        $this->container['page_number'] = $page_number;

        return $this;
    }

    /**
     * Gets bounds
     *
     * @return \BoldSign\Model\Rectangle
     */
    public function getBounds()
    {
        return $this->container['bounds'];
    }

    /**
     * Sets bounds
     *
     * @param \BoldSign\Model\Rectangle $bounds bounds
     *
     * @return self
     */
    public function setBounds($bounds)
    {
        if (is_null($bounds)) {
            throw new \InvalidArgumentException('non-nullable bounds cannot be null');
        }
        $this->container['bounds'] = $bounds;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            array_push($this->openAPINullablesSetToNull, 'id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('id', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            array_push($this->openAPINullablesSetToNull, 'name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets is_required
     *
     * @return bool|null
     */
    public function getIsRequired()
    {
        return $this->container['is_required'];
    }

    /**
     * Sets is_required
     *
     * @param bool|null $is_required is_required
     *
     * @return self
     */
    public function setIsRequired($is_required)
    {
        if (is_null($is_required)) {
            throw new \InvalidArgumentException('non-nullable is_required cannot be null');
        }
        $this->container['is_required'] = $is_required;

        return $this;
    }

    /**
     * Gets is_read_only
     *
     * @return bool|null
     */
    public function getIsReadOnly()
    {
        return $this->container['is_read_only'];
    }

    /**
     * Sets is_read_only
     *
     * @param bool|null $is_read_only is_read_only
     *
     * @return self
     */
    public function setIsReadOnly($is_read_only)
    {
        if (is_null($is_read_only)) {
            throw new \InvalidArgumentException('non-nullable is_read_only cannot be null');
        }
        $this->container['is_read_only'] = $is_read_only;

        return $this;
    }

    /**
     * Gets value
     *
     * @return string|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param string|null $value value
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            array_push($this->openAPINullablesSetToNull, 'value');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('value', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['value'] = $value;

        return $this;
    }

    /**
     * Gets font_size
     *
     * @return float|null
     */
    public function getFontSize()
    {
        return $this->container['font_size'];
    }

    /**
     * Sets font_size
     *
     * @param float|null $font_size font_size
     *
     * @return self
     */
    public function setFontSize($font_size)
    {
        if (is_null($font_size)) {
            throw new \InvalidArgumentException('non-nullable font_size cannot be null');
        }

        if (($font_size < 0)) {
            throw new \InvalidArgumentException('invalid value for $font_size when calling FormField., must be bigger than or equal to 0.');
        }

        $this->container['font_size'] = $font_size;

        return $this;
    }

    /**
     * Gets font
     *
     * @return string|null
     */
    public function getFont()
    {
        return $this->container['font'];
    }

    /**
     * Sets font
     *
     * @param string|null $font font
     *
     * @return self
     */
    public function setFont($font)
    {
        if (is_null($font)) {
            throw new \InvalidArgumentException('non-nullable font cannot be null');
        }
        $allowedValues = $this->getFontAllowableValues();
        if (!in_array($font, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'font', must be one of '%s'",
                    $font,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['font'] = $font;

        return $this;
    }

    /**
     * Gets font_hex_color
     *
     * @return string|null
     */
    public function getFontHexColor()
    {
        return $this->container['font_hex_color'];
    }

    /**
     * Sets font_hex_color
     *
     * @param string|null $font_hex_color font_hex_color
     *
     * @return self
     */
    public function setFontHexColor($font_hex_color)
    {
        if (is_null($font_hex_color)) {
            array_push($this->openAPINullablesSetToNull, 'font_hex_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('font_hex_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['font_hex_color'] = $font_hex_color;

        return $this;
    }

    /**
     * Gets is_bold_font
     *
     * @return bool|null
     */
    public function getIsBoldFont()
    {
        return $this->container['is_bold_font'];
    }

    /**
     * Sets is_bold_font
     *
     * @param bool|null $is_bold_font is_bold_font
     *
     * @return self
     */
    public function setIsBoldFont($is_bold_font)
    {
        if (is_null($is_bold_font)) {
            throw new \InvalidArgumentException('non-nullable is_bold_font cannot be null');
        }
        $this->container['is_bold_font'] = $is_bold_font;

        return $this;
    }

    /**
     * Gets is_italic_font
     *
     * @return bool|null
     */
    public function getIsItalicFont()
    {
        return $this->container['is_italic_font'];
    }

    /**
     * Sets is_italic_font
     *
     * @param bool|null $is_italic_font is_italic_font
     *
     * @return self
     */
    public function setIsItalicFont($is_italic_font)
    {
        if (is_null($is_italic_font)) {
            throw new \InvalidArgumentException('non-nullable is_italic_font cannot be null');
        }
        $this->container['is_italic_font'] = $is_italic_font;

        return $this;
    }

    /**
     * Gets is_under_line_font
     *
     * @return bool|null
     */
    public function getIsUnderLineFont()
    {
        return $this->container['is_under_line_font'];
    }

    /**
     * Sets is_under_line_font
     *
     * @param bool|null $is_under_line_font is_under_line_font
     *
     * @return self
     */
    public function setIsUnderLineFont($is_under_line_font)
    {
        if (is_null($is_under_line_font)) {
            throw new \InvalidArgumentException('non-nullable is_under_line_font cannot be null');
        }
        $this->container['is_under_line_font'] = $is_under_line_font;

        return $this;
    }

    /**
     * Gets line_height
     *
     * @return int|null
     */
    public function getLineHeight()
    {
        return $this->container['line_height'];
    }

    /**
     * Sets line_height
     *
     * @param int|null $line_height line_height
     *
     * @return self
     */
    public function setLineHeight($line_height)
    {
        if (is_null($line_height)) {
            throw new \InvalidArgumentException('non-nullable line_height cannot be null');
        }

        if (($line_height > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $line_height when calling FormField., must be smaller than or equal to 2147483647.');
        }
        if (($line_height < 0)) {
            throw new \InvalidArgumentException('invalid value for $line_height when calling FormField., must be bigger than or equal to 0.');
        }

        $this->container['line_height'] = $line_height;

        return $this;
    }

    /**
     * Gets character_limit
     *
     * @return int|null
     */
    public function getCharacterLimit()
    {
        return $this->container['character_limit'];
    }

    /**
     * Sets character_limit
     *
     * @param int|null $character_limit character_limit
     *
     * @return self
     */
    public function setCharacterLimit($character_limit)
    {
        if (is_null($character_limit)) {
            throw new \InvalidArgumentException('non-nullable character_limit cannot be null');
        }

        if (($character_limit > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $character_limit when calling FormField., must be smaller than or equal to 2147483647.');
        }
        if (($character_limit < 0)) {
            throw new \InvalidArgumentException('invalid value for $character_limit when calling FormField., must be bigger than or equal to 0.');
        }

        $this->container['character_limit'] = $character_limit;

        return $this;
    }

    /**
     * Gets group_name
     *
     * @return string|null
     */
    public function getGroupName()
    {
        return $this->container['group_name'];
    }

    /**
     * Sets group_name
     *
     * @param string|null $group_name group_name
     *
     * @return self
     */
    public function setGroupName($group_name)
    {
        if (is_null($group_name)) {
            array_push($this->openAPINullablesSetToNull, 'group_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('group_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['group_name'] = $group_name;

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label label
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            array_push($this->openAPINullablesSetToNull, 'label');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('label', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['label'] = $label;

        return $this;
    }

    /**
     * Gets place_holder
     *
     * @return string|null
     */
    public function getPlaceHolder()
    {
        return $this->container['place_holder'];
    }

    /**
     * Sets place_holder
     *
     * @param string|null $place_holder place_holder
     *
     * @return self
     */
    public function setPlaceHolder($place_holder)
    {
        if (is_null($place_holder)) {
            array_push($this->openAPINullablesSetToNull, 'place_holder');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('place_holder', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['place_holder'] = $place_holder;

        return $this;
    }

    /**
     * Gets validation_type
     *
     * @return string|null
     */
    public function getValidationType()
    {
        return $this->container['validation_type'];
    }

    /**
     * Sets validation_type
     *
     * @param string|null $validation_type validation_type
     *
     * @return self
     */
    public function setValidationType($validation_type)
    {
        if (is_null($validation_type)) {
            throw new \InvalidArgumentException('non-nullable validation_type cannot be null');
        }
        $allowedValues = $this->getValidationTypeAllowableValues();
        if (!in_array($validation_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'validation_type', must be one of '%s'",
                    $validation_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['validation_type'] = $validation_type;

        return $this;
    }

    /**
     * Gets validation_custom_regex
     *
     * @return string|null
     */
    public function getValidationCustomRegex()
    {
        return $this->container['validation_custom_regex'];
    }

    /**
     * Sets validation_custom_regex
     *
     * @param string|null $validation_custom_regex validation_custom_regex
     *
     * @return self
     */
    public function setValidationCustomRegex($validation_custom_regex)
    {
        if (is_null($validation_custom_regex)) {
            array_push($this->openAPINullablesSetToNull, 'validation_custom_regex');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validation_custom_regex', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validation_custom_regex'] = $validation_custom_regex;

        return $this;
    }

    /**
     * Gets validation_custom_regex_message
     *
     * @return string|null
     */
    public function getValidationCustomRegexMessage()
    {
        return $this->container['validation_custom_regex_message'];
    }

    /**
     * Sets validation_custom_regex_message
     *
     * @param string|null $validation_custom_regex_message validation_custom_regex_message
     *
     * @return self
     */
    public function setValidationCustomRegexMessage($validation_custom_regex_message)
    {
        if (is_null($validation_custom_regex_message)) {
            array_push($this->openAPINullablesSetToNull, 'validation_custom_regex_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('validation_custom_regex_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['validation_custom_regex_message'] = $validation_custom_regex_message;

        return $this;
    }

    /**
     * Gets date_format
     *
     * @return string|null
     */
    public function getDateFormat()
    {
        return $this->container['date_format'];
    }

    /**
     * Sets date_format
     *
     * @param string|null $date_format date_format
     *
     * @return self
     */
    public function setDateFormat($date_format)
    {
        if (is_null($date_format)) {
            array_push($this->openAPINullablesSetToNull, 'date_format');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('date_format', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['date_format'] = $date_format;

        return $this;
    }

    /**
     * Gets time_format
     *
     * @return string|null
     */
    public function getTimeFormat()
    {
        return $this->container['time_format'];
    }

    /**
     * Sets time_format
     *
     * @param string|null $time_format time_format
     *
     * @return self
     */
    public function setTimeFormat($time_format)
    {
        if (is_null($time_format)) {
            array_push($this->openAPINullablesSetToNull, 'time_format');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('time_format', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['time_format'] = $time_format;

        return $this;
    }

    /**
     * Gets image_info
     *
     * @return \BoldSign\Model\ImageInfo|null
     */
    public function getImageInfo()
    {
        return $this->container['image_info'];
    }

    /**
     * Sets image_info
     *
     * @param \BoldSign\Model\ImageInfo|null $image_info image_info
     *
     * @return self
     */
    public function setImageInfo($image_info)
    {
        if (is_null($image_info)) {
            throw new \InvalidArgumentException('non-nullable image_info cannot be null');
        }
        $this->container['image_info'] = $image_info;

        return $this;
    }

    /**
     * Gets attachment_info
     *
     * @return \BoldSign\Model\AttachmentInfo|null
     */
    public function getAttachmentInfo()
    {
        return $this->container['attachment_info'];
    }

    /**
     * Sets attachment_info
     *
     * @param \BoldSign\Model\AttachmentInfo|null $attachment_info attachment_info
     *
     * @return self
     */
    public function setAttachmentInfo($attachment_info)
    {
        if (is_null($attachment_info)) {
            throw new \InvalidArgumentException('non-nullable attachment_info cannot be null');
        }
        $this->container['attachment_info'] = $attachment_info;

        return $this;
    }

    /**
     * Gets editable_date_field_settings
     *
     * @return \BoldSign\Model\EditableDateFieldSettings|null
     */
    public function getEditableDateFieldSettings()
    {
        return $this->container['editable_date_field_settings'];
    }

    /**
     * Sets editable_date_field_settings
     *
     * @param \BoldSign\Model\EditableDateFieldSettings|null $editable_date_field_settings editable_date_field_settings
     *
     * @return self
     */
    public function setEditableDateFieldSettings($editable_date_field_settings)
    {
        if (is_null($editable_date_field_settings)) {
            throw new \InvalidArgumentException('non-nullable editable_date_field_settings cannot be null');
        }
        $this->container['editable_date_field_settings'] = $editable_date_field_settings;

        return $this;
    }

    /**
     * Gets hyperlink_text
     *
     * @return string|null
     */
    public function getHyperlinkText()
    {
        return $this->container['hyperlink_text'];
    }

    /**
     * Sets hyperlink_text
     *
     * @param string|null $hyperlink_text hyperlink_text
     *
     * @return self
     */
    public function setHyperlinkText($hyperlink_text)
    {
        if (is_null($hyperlink_text)) {
            array_push($this->openAPINullablesSetToNull, 'hyperlink_text');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('hyperlink_text', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['hyperlink_text'] = $hyperlink_text;

        return $this;
    }

    /**
     * Gets conditional_rules
     *
     * @return \BoldSign\Model\ConditionalRule[]|null
     */
    public function getConditionalRules()
    {
        return $this->container['conditional_rules'];
    }

    /**
     * Sets conditional_rules
     *
     * @param \BoldSign\Model\ConditionalRule[]|null $conditional_rules conditional_rules
     *
     * @return self
     */
    public function setConditionalRules($conditional_rules)
    {
        if (is_null($conditional_rules)) {
            array_push($this->openAPINullablesSetToNull, 'conditional_rules');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('conditional_rules', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['conditional_rules'] = $conditional_rules;

        return $this;
    }

    /**
     * Gets data_sync_tag
     *
     * @return string|null
     */
    public function getDataSyncTag()
    {
        return $this->container['data_sync_tag'];
    }

    /**
     * Sets data_sync_tag
     *
     * @param string|null $data_sync_tag data_sync_tag
     *
     * @return self
     */
    public function setDataSyncTag($data_sync_tag)
    {
        if (is_null($data_sync_tag)) {
            array_push($this->openAPINullablesSetToNull, 'data_sync_tag');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('data_sync_tag', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['data_sync_tag'] = $data_sync_tag;

        return $this;
    }

    /**
     * Gets dropdown_options
     *
     * @return string[]|null
     */
    public function getDropdownOptions()
    {
        return $this->container['dropdown_options'];
    }

    /**
     * Sets dropdown_options
     *
     * @param string[]|null $dropdown_options dropdown_options
     *
     * @return self
     */
    public function setDropdownOptions($dropdown_options)
    {
        if (is_null($dropdown_options)) {
            array_push($this->openAPINullablesSetToNull, 'dropdown_options');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('dropdown_options', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['dropdown_options'] = $dropdown_options;

        return $this;
    }

    /**
     * Gets text_align
     *
     * @return string|null
     */
    public function getTextAlign()
    {
        return $this->container['text_align'];
    }

    /**
     * Sets text_align
     *
     * @param string|null $text_align text_align
     *
     * @return self
     */
    public function setTextAlign($text_align)
    {
        if (is_null($text_align)) {
            throw new \InvalidArgumentException('non-nullable text_align cannot be null');
        }
        $allowedValues = $this->getTextAlignAllowableValues();
        if (!in_array($text_align, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'text_align', must be one of '%s'",
                    $text_align,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['text_align'] = $text_align;

        return $this;
    }

    /**
     * Gets text_direction
     *
     * @return string|null
     */
    public function getTextDirection()
    {
        return $this->container['text_direction'];
    }

    /**
     * Sets text_direction
     *
     * @param string|null $text_direction text_direction
     *
     * @return self
     */
    public function setTextDirection($text_direction)
    {
        if (is_null($text_direction)) {
            throw new \InvalidArgumentException('non-nullable text_direction cannot be null');
        }
        $allowedValues = $this->getTextDirectionAllowableValues();
        if (!in_array($text_direction, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'text_direction', must be one of '%s'",
                    $text_direction,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['text_direction'] = $text_direction;

        return $this;
    }

    /**
     * Gets character_spacing
     *
     * @return float|null
     */
    public function getCharacterSpacing()
    {
        return $this->container['character_spacing'];
    }

    /**
     * Sets character_spacing
     *
     * @param float|null $character_spacing character_spacing
     *
     * @return self
     */
    public function setCharacterSpacing($character_spacing)
    {
        if (is_null($character_spacing)) {
            throw new \InvalidArgumentException('non-nullable character_spacing cannot be null');
        }
        $this->container['character_spacing'] = $character_spacing;

        return $this;
    }

    /**
     * Gets background_hex_color
     *
     * @return string|null
     */
    public function getBackgroundHexColor()
    {
        return $this->container['background_hex_color'];
    }

    /**
     * Sets background_hex_color
     *
     * @param string|null $background_hex_color background_hex_color
     *
     * @return self
     */
    public function setBackgroundHexColor($background_hex_color)
    {
        if (is_null($background_hex_color)) {
            array_push($this->openAPINullablesSetToNull, 'background_hex_color');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('background_hex_color', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['background_hex_color'] = $background_hex_color;

        return $this;
    }

    /**
     * Gets tab_index
     *
     * @return int|null
     */
    public function getTabIndex()
    {
        return $this->container['tab_index'];
    }

    /**
     * Sets tab_index
     *
     * @param int|null $tab_index tab_index
     *
     * @return self
     */
    public function setTabIndex($tab_index)
    {
        if (is_null($tab_index)) {
            array_push($this->openAPINullablesSetToNull, 'tab_index');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('tab_index', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($tab_index) && ($tab_index > 2147483647)) {
            throw new \InvalidArgumentException('invalid value for $tab_index when calling FormField., must be smaller than or equal to 2147483647.');
        }
        if (!is_null($tab_index) && ($tab_index < -1)) {
            throw new \InvalidArgumentException('invalid value for $tab_index when calling FormField., must be bigger than or equal to -1.');
        }

        $this->container['tab_index'] = $tab_index;

        return $this;
    }

    /**
     * Gets formula_field_settings
     *
     * @return \BoldSign\Model\FormulaFieldSettings|null
     */
    public function getFormulaFieldSettings()
    {
        return $this->container['formula_field_settings'];
    }

    /**
     * Sets formula_field_settings
     *
     * @param \BoldSign\Model\FormulaFieldSettings|null $formula_field_settings formula_field_settings
     *
     * @return self
     */
    public function setFormulaFieldSettings($formula_field_settings)
    {
        if (is_null($formula_field_settings)) {
            throw new \InvalidArgumentException('non-nullable formula_field_settings cannot be null');
        }
        $this->container['formula_field_settings'] = $formula_field_settings;

        return $this;
    }

    /**
     * Gets resize_option
     *
     * @return string|null
     */
    public function getResizeOption()
    {
        return $this->container['resize_option'];
    }

    /**
     * Sets resize_option
     *
     * @param string|null $resize_option resize_option
     *
     * @return self
     */
    public function setResizeOption($resize_option)
    {
        if (is_null($resize_option)) {
            array_push($this->openAPINullablesSetToNull, 'resize_option');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('resize_option', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getResizeOptionAllowableValues();
        if (!is_null($resize_option) && !in_array($resize_option, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'resize_option', must be one of '%s'",
                    $resize_option,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['resize_option'] = $resize_option;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


