<?php
/**
 * Role
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BoldSign API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace BoldSign\Model;

use \ArrayAccess;
use \BoldSign\ObjectSerializer;

/**
 * Role Class Doc Comment
 *
 * @category Class
 * @package  BoldSign
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class Role implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Role';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'role_index' => 'int',
        'signer_name' => 'string',
        'signer_order' => 'int',
        'signer_email' => 'string',
        'host_email' => 'string',
        'private_message' => 'string',
        'authentication_code' => 'string',
        'enable_email_otp' => 'bool',
        'authentication_type' => 'string',
        'phone_number' => '\BoldSign\Model\PhoneNumber',
        'delivery_mode' => 'string',
        'signer_type' => 'string',
        'signer_role' => 'string',
        'allow_field_configuration' => 'bool',
        'form_fields' => '\BoldSign\Model\FormField[]',
        'existing_form_fields' => '\BoldSign\Model\ExistingFormField[]',
        'identity_verification_settings' => '\BoldSign\Model\IdentityVerificationSettings',
        'language' => 'int',
        'locale' => 'string',
        'recipient_notification_settings' => '\BoldSign\Model\RecipientNotificationSettings',
        'authentication_retry_count' => 'int',
        'enable_qes' => 'bool',
        'authentication_settings' => '\BoldSign\Model\AuthenticationSettings'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'role_index' => 'int32',
        'signer_name' => null,
        'signer_order' => 'int32',
        'signer_email' => null,
        'host_email' => null,
        'private_message' => null,
        'authentication_code' => null,
        'enable_email_otp' => null,
        'authentication_type' => null,
        'phone_number' => null,
        'delivery_mode' => null,
        'signer_type' => null,
        'signer_role' => null,
        'allow_field_configuration' => null,
        'form_fields' => null,
        'existing_form_fields' => null,
        'identity_verification_settings' => null,
        'language' => 'int32',
        'locale' => null,
        'recipient_notification_settings' => null,
        'authentication_retry_count' => 'int32',
        'enable_qes' => null,
        'authentication_settings' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'role_index' => true,
        'signer_name' => true,
        'signer_order' => false,
        'signer_email' => true,
        'host_email' => true,
        'private_message' => true,
        'authentication_code' => true,
        'enable_email_otp' => false,
        'authentication_type' => false,
        'phone_number' => false,
        'delivery_mode' => false,
        'signer_type' => true,
        'signer_role' => true,
        'allow_field_configuration' => true,
        'form_fields' => true,
        'existing_form_fields' => true,
        'identity_verification_settings' => false,
        'language' => false,
        'locale' => false,
        'recipient_notification_settings' => false,
        'authentication_retry_count' => true,
        'enable_qes' => true,
        'authentication_settings' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'role_index' => 'roleIndex',
        'signer_name' => 'signerName',
        'signer_order' => 'signerOrder',
        'signer_email' => 'signerEmail',
        'host_email' => 'hostEmail',
        'private_message' => 'privateMessage',
        'authentication_code' => 'authenticationCode',
        'enable_email_otp' => 'enableEmailOTP',
        'authentication_type' => 'authenticationType',
        'phone_number' => 'phoneNumber',
        'delivery_mode' => 'deliveryMode',
        'signer_type' => 'signerType',
        'signer_role' => 'signerRole',
        'allow_field_configuration' => 'allowFieldConfiguration',
        'form_fields' => 'formFields',
        'existing_form_fields' => 'existingFormFields',
        'identity_verification_settings' => 'identityVerificationSettings',
        'language' => 'language',
        'locale' => 'locale',
        'recipient_notification_settings' => 'recipientNotificationSettings',
        'authentication_retry_count' => 'authenticationRetryCount',
        'enable_qes' => 'enableQes',
        'authentication_settings' => 'authenticationSettings'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'role_index' => 'setRoleIndex',
        'signer_name' => 'setSignerName',
        'signer_order' => 'setSignerOrder',
        'signer_email' => 'setSignerEmail',
        'host_email' => 'setHostEmail',
        'private_message' => 'setPrivateMessage',
        'authentication_code' => 'setAuthenticationCode',
        'enable_email_otp' => 'setEnableEmailOtp',
        'authentication_type' => 'setAuthenticationType',
        'phone_number' => 'setPhoneNumber',
        'delivery_mode' => 'setDeliveryMode',
        'signer_type' => 'setSignerType',
        'signer_role' => 'setSignerRole',
        'allow_field_configuration' => 'setAllowFieldConfiguration',
        'form_fields' => 'setFormFields',
        'existing_form_fields' => 'setExistingFormFields',
        'identity_verification_settings' => 'setIdentityVerificationSettings',
        'language' => 'setLanguage',
        'locale' => 'setLocale',
        'recipient_notification_settings' => 'setRecipientNotificationSettings',
        'authentication_retry_count' => 'setAuthenticationRetryCount',
        'enable_qes' => 'setEnableQes',
        'authentication_settings' => 'setAuthenticationSettings'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'role_index' => 'getRoleIndex',
        'signer_name' => 'getSignerName',
        'signer_order' => 'getSignerOrder',
        'signer_email' => 'getSignerEmail',
        'host_email' => 'getHostEmail',
        'private_message' => 'getPrivateMessage',
        'authentication_code' => 'getAuthenticationCode',
        'enable_email_otp' => 'getEnableEmailOtp',
        'authentication_type' => 'getAuthenticationType',
        'phone_number' => 'getPhoneNumber',
        'delivery_mode' => 'getDeliveryMode',
        'signer_type' => 'getSignerType',
        'signer_role' => 'getSignerRole',
        'allow_field_configuration' => 'getAllowFieldConfiguration',
        'form_fields' => 'getFormFields',
        'existing_form_fields' => 'getExistingFormFields',
        'identity_verification_settings' => 'getIdentityVerificationSettings',
        'language' => 'getLanguage',
        'locale' => 'getLocale',
        'recipient_notification_settings' => 'getRecipientNotificationSettings',
        'authentication_retry_count' => 'getAuthenticationRetryCount',
        'enable_qes' => 'getEnableQes',
        'authentication_settings' => 'getAuthenticationSettings'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const AUTHENTICATION_TYPE_NONE = 'None';
    public const AUTHENTICATION_TYPE_EMAIL_OTP = 'EmailOTP';
    public const AUTHENTICATION_TYPE_ACCESS_CODE = 'AccessCode';
    public const AUTHENTICATION_TYPE_SMSOTP = 'SMSOTP';
    public const AUTHENTICATION_TYPE_ID_VERIFICATION = 'IdVerification';
    public const DELIVERY_MODE_EMAIL = 'Email';
    public const DELIVERY_MODE_SMS = 'SMS';
    public const DELIVERY_MODE_EMAIL_AND_SMS = 'EmailAndSMS';
    public const DELIVERY_MODE_WHATS_APP = 'WhatsApp';
    public const SIGNER_TYPE_SIGNER = 'Signer';
    public const SIGNER_TYPE_REVIEWER = 'Reviewer';
    public const SIGNER_TYPE_IN_PERSON_SIGNER = 'InPersonSigner';
    public const SIGNER_TYPE_NULL = 'null';
    public const LANGUAGE_0 = 0;
    public const LANGUAGE_1 = 1;
    public const LANGUAGE_2 = 2;
    public const LANGUAGE_3 = 3;
    public const LANGUAGE_4 = 4;
    public const LANGUAGE_5 = 5;
    public const LANGUAGE_6 = 6;
    public const LANGUAGE_7 = 7;
    public const LANGUAGE_8 = 8;
    public const LANGUAGE_9 = 9;
    public const LANGUAGE_10 = 10;
    public const LANGUAGE_11 = 11;
    public const LANGUAGE_12 = 12;
    public const LANGUAGE_13 = 13;
    public const LANGUAGE_14 = 14;
    public const LANGUAGE_15 = 15;
    public const LOCALE_EN = 'EN';
    public const LOCALE_NO = 'NO';
    public const LOCALE_FR = 'FR';
    public const LOCALE_DE = 'DE';
    public const LOCALE_ES = 'ES';
    public const LOCALE_BG = 'BG';
    public const LOCALE_CS = 'CS';
    public const LOCALE_DA = 'DA';
    public const LOCALE_IT = 'IT';
    public const LOCALE_NL = 'NL';
    public const LOCALE_PL = 'PL';
    public const LOCALE_PT = 'PT';
    public const LOCALE_RO = 'RO';
    public const LOCALE_RU = 'RU';
    public const LOCALE_SV = 'SV';
    public const LOCALE__DEFAULT = 'Default';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getAuthenticationTypeAllowableValues()
    {
        return [
            self::AUTHENTICATION_TYPE_NONE,
            self::AUTHENTICATION_TYPE_EMAIL_OTP,
            self::AUTHENTICATION_TYPE_ACCESS_CODE,
            self::AUTHENTICATION_TYPE_SMSOTP,
            self::AUTHENTICATION_TYPE_ID_VERIFICATION,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getDeliveryModeAllowableValues()
    {
        return [
            self::DELIVERY_MODE_EMAIL,
            self::DELIVERY_MODE_SMS,
            self::DELIVERY_MODE_EMAIL_AND_SMS,
            self::DELIVERY_MODE_WHATS_APP,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getSignerTypeAllowableValues()
    {
        return [
            self::SIGNER_TYPE_SIGNER,
            self::SIGNER_TYPE_REVIEWER,
            self::SIGNER_TYPE_IN_PERSON_SIGNER,
            self::SIGNER_TYPE_NULL,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLanguageAllowableValues()
    {
        return [
            self::LANGUAGE_0,
            self::LANGUAGE_1,
            self::LANGUAGE_2,
            self::LANGUAGE_3,
            self::LANGUAGE_4,
            self::LANGUAGE_5,
            self::LANGUAGE_6,
            self::LANGUAGE_7,
            self::LANGUAGE_8,
            self::LANGUAGE_9,
            self::LANGUAGE_10,
            self::LANGUAGE_11,
            self::LANGUAGE_12,
            self::LANGUAGE_13,
            self::LANGUAGE_14,
            self::LANGUAGE_15,
        ];
    }

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getLocaleAllowableValues()
    {
        return [
            self::LOCALE_EN,
            self::LOCALE_NO,
            self::LOCALE_FR,
            self::LOCALE_DE,
            self::LOCALE_ES,
            self::LOCALE_BG,
            self::LOCALE_CS,
            self::LOCALE_DA,
            self::LOCALE_IT,
            self::LOCALE_NL,
            self::LOCALE_PL,
            self::LOCALE_PT,
            self::LOCALE_RO,
            self::LOCALE_RU,
            self::LOCALE_SV,
            self::LOCALE__DEFAULT,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('role_index', $data ?? [], null);
        $this->setIfExists('signer_name', $data ?? [], null);
        $this->setIfExists('signer_order', $data ?? [], null);
        $this->setIfExists('signer_email', $data ?? [], null);
        $this->setIfExists('host_email', $data ?? [], null);
        $this->setIfExists('private_message', $data ?? [], null);
        $this->setIfExists('authentication_code', $data ?? [], null);
        $this->setIfExists('enable_email_otp', $data ?? [], null);
        $this->setIfExists('authentication_type', $data ?? [], null);
        $this->setIfExists('phone_number', $data ?? [], null);
        $this->setIfExists('delivery_mode', $data ?? [], null);
        $this->setIfExists('signer_type', $data ?? [], null);
        $this->setIfExists('signer_role', $data ?? [], null);
        $this->setIfExists('allow_field_configuration', $data ?? [], null);
        $this->setIfExists('form_fields', $data ?? [], null);
        $this->setIfExists('existing_form_fields', $data ?? [], null);
        $this->setIfExists('identity_verification_settings', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('locale', $data ?? [], null);
        $this->setIfExists('recipient_notification_settings', $data ?? [], null);
        $this->setIfExists('authentication_retry_count', $data ?? [], null);
        $this->setIfExists('enable_qes', $data ?? [], null);
        $this->setIfExists('authentication_settings', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['role_index']) && ($this->container['role_index'] > 50)) {
            $invalidProperties[] = "invalid value for 'role_index', must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['role_index']) && ($this->container['role_index'] < 1)) {
            $invalidProperties[] = "invalid value for 'role_index', must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['private_message']) && (mb_strlen($this->container['private_message']) > 5000)) {
            $invalidProperties[] = "invalid value for 'private_message', the character length must be smaller than or equal to 5000.";
        }

        if (!is_null($this->container['authentication_code']) && (mb_strlen($this->container['authentication_code']) > 50)) {
            $invalidProperties[] = "invalid value for 'authentication_code', the character length must be smaller than or equal to 50.";
        }

        $allowedValues = $this->getAuthenticationTypeAllowableValues();
        if (!is_null($this->container['authentication_type']) && !in_array($this->container['authentication_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'authentication_type', must be one of '%s'",
                $this->container['authentication_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getDeliveryModeAllowableValues();
        if (!is_null($this->container['delivery_mode']) && !in_array($this->container['delivery_mode'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'delivery_mode', must be one of '%s'",
                $this->container['delivery_mode'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getSignerTypeAllowableValues();
        if (!is_null($this->container['signer_type']) && !in_array($this->container['signer_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'signer_type', must be one of '%s'",
                $this->container['signer_type'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLanguageAllowableValues();
        if (!is_null($this->container['language']) && !in_array($this->container['language'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'language', must be one of '%s'",
                $this->container['language'],
                implode("', '", $allowedValues)
            );
        }

        $allowedValues = $this->getLocaleAllowableValues();
        if (!is_null($this->container['locale']) && !in_array($this->container['locale'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'locale', must be one of '%s'",
                $this->container['locale'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['authentication_retry_count']) && ($this->container['authentication_retry_count'] > 10)) {
            $invalidProperties[] = "invalid value for 'authentication_retry_count', must be smaller than or equal to 10.";
        }

        if (!is_null($this->container['authentication_retry_count']) && ($this->container['authentication_retry_count'] < 1)) {
            $invalidProperties[] = "invalid value for 'authentication_retry_count', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets role_index
     *
     * @return int|null
     */
    public function getRoleIndex()
    {
        return $this->container['role_index'];
    }

    /**
     * Sets role_index
     *
     * @param int|null $role_index role_index
     *
     * @return self
     */
    public function setRoleIndex($role_index)
    {
        if (is_null($role_index)) {
            array_push($this->openAPINullablesSetToNull, 'role_index');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('role_index', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($role_index) && ($role_index > 50)) {
            throw new \InvalidArgumentException('invalid value for $role_index when calling Role., must be smaller than or equal to 50.');
        }
        if (!is_null($role_index) && ($role_index < 1)) {
            throw new \InvalidArgumentException('invalid value for $role_index when calling Role., must be bigger than or equal to 1.');
        }

        $this->container['role_index'] = $role_index;

        return $this;
    }

    /**
     * Gets signer_name
     *
     * @return string|null
     */
    public function getSignerName()
    {
        return $this->container['signer_name'];
    }

    /**
     * Sets signer_name
     *
     * @param string|null $signer_name signer_name
     *
     * @return self
     */
    public function setSignerName($signer_name)
    {
        if (is_null($signer_name)) {
            array_push($this->openAPINullablesSetToNull, 'signer_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('signer_name', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['signer_name'] = $signer_name;

        return $this;
    }

    /**
     * Gets signer_order
     *
     * @return int|null
     */
    public function getSignerOrder()
    {
        return $this->container['signer_order'];
    }

    /**
     * Sets signer_order
     *
     * @param int|null $signer_order signer_order
     *
     * @return self
     */
    public function setSignerOrder($signer_order)
    {
        if (is_null($signer_order)) {
            throw new \InvalidArgumentException('non-nullable signer_order cannot be null');
        }
        $this->container['signer_order'] = $signer_order;

        return $this;
    }

    /**
     * Gets signer_email
     *
     * @return string|null
     */
    public function getSignerEmail()
    {
        return $this->container['signer_email'];
    }

    /**
     * Sets signer_email
     *
     * @param string|null $signer_email signer_email
     *
     * @return self
     */
    public function setSignerEmail($signer_email)
    {
        if (is_null($signer_email)) {
            array_push($this->openAPINullablesSetToNull, 'signer_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('signer_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['signer_email'] = $signer_email;

        return $this;
    }

    /**
     * Gets host_email
     *
     * @return string|null
     */
    public function getHostEmail()
    {
        return $this->container['host_email'];
    }

    /**
     * Sets host_email
     *
     * @param string|null $host_email host_email
     *
     * @return self
     */
    public function setHostEmail($host_email)
    {
        if (is_null($host_email)) {
            array_push($this->openAPINullablesSetToNull, 'host_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('host_email', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['host_email'] = $host_email;

        return $this;
    }

    /**
     * Gets private_message
     *
     * @return string|null
     */
    public function getPrivateMessage()
    {
        return $this->container['private_message'];
    }

    /**
     * Sets private_message
     *
     * @param string|null $private_message private_message
     *
     * @return self
     */
    public function setPrivateMessage($private_message)
    {
        if (is_null($private_message)) {
            array_push($this->openAPINullablesSetToNull, 'private_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('private_message', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($private_message) && (mb_strlen($private_message) > 5000)) {
            throw new \InvalidArgumentException('invalid length for $private_message when calling Role., must be smaller than or equal to 5000.');
        }

        $this->container['private_message'] = $private_message;

        return $this;
    }

    /**
     * Gets authentication_code
     *
     * @return string|null
     */
    public function getAuthenticationCode()
    {
        return $this->container['authentication_code'];
    }

    /**
     * Sets authentication_code
     *
     * @param string|null $authentication_code authentication_code
     *
     * @return self
     */
    public function setAuthenticationCode($authentication_code)
    {
        if (is_null($authentication_code)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_code');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_code', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        if (!is_null($authentication_code) && (mb_strlen($authentication_code) > 50)) {
            throw new \InvalidArgumentException('invalid length for $authentication_code when calling Role., must be smaller than or equal to 50.');
        }

        $this->container['authentication_code'] = $authentication_code;

        return $this;
    }

    /**
     * Gets enable_email_otp
     *
     * @return bool|null
     */
    public function getEnableEmailOtp()
    {
        return $this->container['enable_email_otp'];
    }

    /**
     * Sets enable_email_otp
     *
     * @param bool|null $enable_email_otp enable_email_otp
     *
     * @return self
     */
    public function setEnableEmailOtp($enable_email_otp)
    {
        if (is_null($enable_email_otp)) {
            throw new \InvalidArgumentException('non-nullable enable_email_otp cannot be null');
        }
        $this->container['enable_email_otp'] = $enable_email_otp;

        return $this;
    }

    /**
     * Gets authentication_type
     *
     * @return string|null
     */
    public function getAuthenticationType()
    {
        return $this->container['authentication_type'];
    }

    /**
     * Sets authentication_type
     *
     * @param string|null $authentication_type authentication_type
     *
     * @return self
     */
    public function setAuthenticationType($authentication_type)
    {
        if (is_null($authentication_type)) {
            throw new \InvalidArgumentException('non-nullable authentication_type cannot be null');
        }
        $allowedValues = $this->getAuthenticationTypeAllowableValues();
        if (!in_array($authentication_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'authentication_type', must be one of '%s'",
                    $authentication_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['authentication_type'] = $authentication_type;

        return $this;
    }

    /**
     * Gets phone_number
     *
     * @return \BoldSign\Model\PhoneNumber|null
     */
    public function getPhoneNumber()
    {
        return $this->container['phone_number'];
    }

    /**
     * Sets phone_number
     *
     * @param \BoldSign\Model\PhoneNumber|null $phone_number phone_number
     *
     * @return self
     */
    public function setPhoneNumber($phone_number)
    {
        if (is_null($phone_number)) {
            throw new \InvalidArgumentException('non-nullable phone_number cannot be null');
        }
        $this->container['phone_number'] = $phone_number;

        return $this;
    }

    /**
     * Gets delivery_mode
     *
     * @return string|null
     */
    public function getDeliveryMode()
    {
        return $this->container['delivery_mode'];
    }

    /**
     * Sets delivery_mode
     *
     * @param string|null $delivery_mode delivery_mode
     *
     * @return self
     */
    public function setDeliveryMode($delivery_mode)
    {
        if (is_null($delivery_mode)) {
            throw new \InvalidArgumentException('non-nullable delivery_mode cannot be null');
        }
        $allowedValues = $this->getDeliveryModeAllowableValues();
        if (!in_array($delivery_mode, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'delivery_mode', must be one of '%s'",
                    $delivery_mode,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['delivery_mode'] = $delivery_mode;

        return $this;
    }

    /**
     * Gets signer_type
     *
     * @return string|null
     */
    public function getSignerType()
    {
        return $this->container['signer_type'];
    }

    /**
     * Sets signer_type
     *
     * @param string|null $signer_type signer_type
     *
     * @return self
     */
    public function setSignerType($signer_type)
    {
        if (is_null($signer_type)) {
            array_push($this->openAPINullablesSetToNull, 'signer_type');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('signer_type', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $allowedValues = $this->getSignerTypeAllowableValues();
        if (!is_null($signer_type) && !in_array($signer_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'signer_type', must be one of '%s'",
                    $signer_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['signer_type'] = $signer_type;

        return $this;
    }

    /**
     * Gets signer_role
     *
     * @return string|null
     */
    public function getSignerRole()
    {
        return $this->container['signer_role'];
    }

    /**
     * Sets signer_role
     *
     * @param string|null $signer_role signer_role
     *
     * @return self
     */
    public function setSignerRole($signer_role)
    {
        if (is_null($signer_role)) {
            array_push($this->openAPINullablesSetToNull, 'signer_role');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('signer_role', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['signer_role'] = $signer_role;

        return $this;
    }

    /**
     * Gets allow_field_configuration
     *
     * @return bool|null
     */
    public function getAllowFieldConfiguration()
    {
        return $this->container['allow_field_configuration'];
    }

    /**
     * Sets allow_field_configuration
     *
     * @param bool|null $allow_field_configuration allow_field_configuration
     *
     * @return self
     */
    public function setAllowFieldConfiguration($allow_field_configuration)
    {
        if (is_null($allow_field_configuration)) {
            array_push($this->openAPINullablesSetToNull, 'allow_field_configuration');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allow_field_configuration', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allow_field_configuration'] = $allow_field_configuration;

        return $this;
    }

    /**
     * Gets form_fields
     *
     * @return \BoldSign\Model\FormField[]|null
     */
    public function getFormFields()
    {
        return $this->container['form_fields'];
    }

    /**
     * Sets form_fields
     *
     * @param \BoldSign\Model\FormField[]|null $form_fields form_fields
     *
     * @return self
     */
    public function setFormFields($form_fields)
    {
        if (is_null($form_fields)) {
            array_push($this->openAPINullablesSetToNull, 'form_fields');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('form_fields', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['form_fields'] = $form_fields;

        return $this;
    }

    /**
     * Gets existing_form_fields
     *
     * @return \BoldSign\Model\ExistingFormField[]|null
     */
    public function getExistingFormFields()
    {
        return $this->container['existing_form_fields'];
    }

    /**
     * Sets existing_form_fields
     *
     * @param \BoldSign\Model\ExistingFormField[]|null $existing_form_fields existing_form_fields
     *
     * @return self
     */
    public function setExistingFormFields($existing_form_fields)
    {
        if (is_null($existing_form_fields)) {
            array_push($this->openAPINullablesSetToNull, 'existing_form_fields');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('existing_form_fields', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['existing_form_fields'] = $existing_form_fields;

        return $this;
    }

    /**
     * Gets identity_verification_settings
     *
     * @return \BoldSign\Model\IdentityVerificationSettings|null
     */
    public function getIdentityVerificationSettings()
    {
        return $this->container['identity_verification_settings'];
    }

    /**
     * Sets identity_verification_settings
     *
     * @param \BoldSign\Model\IdentityVerificationSettings|null $identity_verification_settings identity_verification_settings
     *
     * @return self
     */
    public function setIdentityVerificationSettings($identity_verification_settings)
    {
        if (is_null($identity_verification_settings)) {
            throw new \InvalidArgumentException('non-nullable identity_verification_settings cannot be null');
        }
        $this->container['identity_verification_settings'] = $identity_verification_settings;

        return $this;
    }

    /**
     * Gets language
     *
     * @return int|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param int|null $language <p>Description:</p><ul><li><i>0</i> - None</li><li><i>1</i> - English</li><li><i>2</i> - Spanish</li><li><i>3</i> - German</li><li><i>4</i> - French</li><li><i>5</i> - Romanian</li><li><i>6</i> - Norwegian</li><li><i>7</i> - Bulgarian</li><li><i>8</i> - Italian</li><li><i>9</i> - Danish</li><li><i>10</i> - Polish</li><li><i>11</i> - Portuguese</li><li><i>12</i> - Czech</li><li><i>13</i> - Dutch</li><li><i>14</i> - Swedish</li><li><i>15</i> - Russian</li></ul>
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $allowedValues = $this->getLanguageAllowableValues();
        if (!in_array($language, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'language', must be one of '%s'",
                    $language,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets locale
     *
     * @return string|null
     */
    public function getLocale()
    {
        return $this->container['locale'];
    }

    /**
     * Sets locale
     *
     * @param string|null $locale locale
     *
     * @return self
     */
    public function setLocale($locale)
    {
        if (is_null($locale)) {
            throw new \InvalidArgumentException('non-nullable locale cannot be null');
        }
        $allowedValues = $this->getLocaleAllowableValues();
        if (!in_array($locale, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'locale', must be one of '%s'",
                    $locale,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['locale'] = $locale;

        return $this;
    }

    /**
     * Gets recipient_notification_settings
     *
     * @return \BoldSign\Model\RecipientNotificationSettings|null
     */
    public function getRecipientNotificationSettings()
    {
        return $this->container['recipient_notification_settings'];
    }

    /**
     * Sets recipient_notification_settings
     *
     * @param \BoldSign\Model\RecipientNotificationSettings|null $recipient_notification_settings recipient_notification_settings
     *
     * @return self
     */
    public function setRecipientNotificationSettings($recipient_notification_settings)
    {
        if (is_null($recipient_notification_settings)) {
            throw new \InvalidArgumentException('non-nullable recipient_notification_settings cannot be null');
        }
        $this->container['recipient_notification_settings'] = $recipient_notification_settings;

        return $this;
    }

    /**
     * Gets authentication_retry_count
     *
     * @return int|null
     */
    public function getAuthenticationRetryCount()
    {
        return $this->container['authentication_retry_count'];
    }

    /**
     * Sets authentication_retry_count
     *
     * @param int|null $authentication_retry_count authentication_retry_count
     *
     * @return self
     */
    public function setAuthenticationRetryCount($authentication_retry_count)
    {
        if (is_null($authentication_retry_count)) {
            array_push($this->openAPINullablesSetToNull, 'authentication_retry_count');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('authentication_retry_count', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($authentication_retry_count) && ($authentication_retry_count > 10)) {
            throw new \InvalidArgumentException('invalid value for $authentication_retry_count when calling Role., must be smaller than or equal to 10.');
        }
        if (!is_null($authentication_retry_count) && ($authentication_retry_count < 1)) {
            throw new \InvalidArgumentException('invalid value for $authentication_retry_count when calling Role., must be bigger than or equal to 1.');
        }

        $this->container['authentication_retry_count'] = $authentication_retry_count;

        return $this;
    }

    /**
     * Gets enable_qes
     *
     * @return bool|null
     */
    public function getEnableQes()
    {
        return $this->container['enable_qes'];
    }

    /**
     * Sets enable_qes
     *
     * @param bool|null $enable_qes enable_qes
     *
     * @return self
     */
    public function setEnableQes($enable_qes)
    {
        if (is_null($enable_qes)) {
            array_push($this->openAPINullablesSetToNull, 'enable_qes');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('enable_qes', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['enable_qes'] = $enable_qes;

        return $this;
    }

    /**
     * Gets authentication_settings
     *
     * @return \BoldSign\Model\AuthenticationSettings|null
     */
    public function getAuthenticationSettings()
    {
        return $this->container['authentication_settings'];
    }

    /**
     * Sets authentication_settings
     *
     * @param \BoldSign\Model\AuthenticationSettings|null $authentication_settings authentication_settings
     *
     * @return self
     */
    public function setAuthenticationSettings($authentication_settings)
    {
        if (is_null($authentication_settings)) {
            throw new \InvalidArgumentException('non-nullable authentication_settings cannot be null');
        }
        $this->container['authentication_settings'] = $authentication_settings;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


